name: Android Tests

on:
  push:
    branches:
      - release/v2  # or the branch you want to trigger the tests on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          distribution-url: 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz'

      - name: Build and run tests
        run: |
          chmod +x ./gradlew
          ./gradlew test
