name: Android Tests
on:
  push:
    branches:
      - release/v2  # or the branch you want to trigger the tests on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'sdk'

    - name: Build and run tests
      run: |
        chmod +x ./gradlew
        ./gradlew test